### ISSUE TITLE
Checks fail with duckplyr

### ISSUE THREAD

**Issue by krlmlr** [openpharma/mtdesign#10]
The duckplyr package is aimed to be a drop-in replacement for dplyr, with full behavior compatibility. To assert that, I'm running checks with a rigged version of dplyr. This package fails its checks in this scenario.

Learn more about duckplyr: https://duckplyr.tidyverse.org/ .

From the error message, I can't tell immediately what the cause of the failure is. (It just says "Killed", I've tried many times.) I'd appreciate your help: can you please help understand why the check process is being killed? Ideally, we could digest a reproducible example that shows how duckplyr is behaving differently from dplyr (or perhaps just much slower or using too much memory) in your use case.

The modified dplyr version can be installed with any of:

```r
pak::pak("krlmlr/dplyr@f-revdep-duckplyr")
# remotes::install_github("krlmlr/dplyr@f-revdep-duckplyr")
# devtools::install_github("krlmlr/dplyr@f-revdep-duckplyr")
```

Thanks a lot for your help! Please let me know if you have any questions.

Tracker: https://github.com/tidyverse/duckplyr/issues/297.

**Comment by Puzzled-Face** [comment]
Alas, this is out-of-scope with regard to `mtdesign`.
