### ISSUE TITLE
Undefined variable in log message resulting in error

### ISSUE THREAD

**Issue by daroczig** [openpharma/mtdesign#8]
Hi,

Although I see you have moved away from using `logger`, but the CRAN version still references it, and the reverse dependency checks are failing due to https://github.com/openpharma/mtdesign/blob/main/R/functions.R#L117

I think the problem is that you are explicitly logging `bounds`, while it might not have been previously created -- only if `(is.na(nMin) | is.na(nMax))`.

So thus the logging attempt fails. IMO this was not previously captured due to no one running the fn with DEBUG log level and with both `nMin` and `nMax` defined? Anyway, I'd highly appreciate an update on CRAN so that the reverse dependency check can pass :pray: 

I'm also happy to discuss your performance issues with `logger` if it's still on the table :)

**Comment by daroczig** [comment]
To replicate with the current version:

```r
> futile.logger::flog.threshold("TRACE")
> y <- createGrid(p0 = 0.1, p1 = 0.4, alpha = 0.1, beta = 0.1, nMin = 20, nMax = 30)
mtdesign 2024-03-04 14:28:57 DEBUG createGrid: Entry
Error in createGrid(p0 = 0.1, p1 = 0.4, alpha = 0.1, beta = 0.1, nMin = 20,  : 
  object 'bounds' not found
```

**Comment by Puzzled-Face** [comment]
Thank you.  I've fixed this in the latest development release, which should soon be released on CRAN.  Unfortunately, I don't have the bandwidth to work on the problem with `logger`, but I appreciate your interest.
